"""
Advent of Code Day 1, Part 1

Input:
    two1nine
    eightwothree
    abcone2threexyz
    xtwone3four
    4nineeightseven2
    zoneight234
    7pqrstsixteen

Output:
    29 + 83 + 13 + 24 + 42 + 14 + 76 = 281
"""

FILE = "12-2023\day1\data.txt"

# Get a list from the files lines
with open(FILE) as file:
    lines = file.readlines()
    lines = [line.strip() for line in lines]
    file.close()


nums = []
num_dict = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "seven": 7, "eight": 8, "nine": 9}
num_list = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]

# Get the first and last number found in each line
for line in lines:

    word_positions = {}
    first_number = None
    last_number = None

    for index in range(len(line)):

        # First check for spelled words with the same process
        for num in num_list:
            if line[index:].startswith(num):

                if not first_number:
                    first_number = str(num_dict[num])
                    last_number = str(num_dict[num])
                    break
                else:
                    last_number = str(num_dict[num])
                    break
        
        # Will only execute if a digit
        if line[index].isdigit():
            if not first_number:
                first_number = line[index]
                last_number = line[index]
            else:
                last_number = line[index]

    # Numbers generated by line
    nums.append(int(first_number+last_number))

# Results
print(sum(nums))
