"""
Advent of Code Day 1, Part 1

Input:
    1abc2
    pqr3stu8vwx
    a1b2c3d4e5f
    treb7uchet

Output:
    12+38+15+77 = 142
"""

FILE = "12-2023\data.txt"

# Get a list from the files lines
with open(FILE) as file:
    lines = file.readlines()
    lines = [line.strip() for line in lines]
    file.close()


nums = []

# Get the first and last number found in each line
for line in lines:
    first_number = None
    last_number = None
    for char in line:
        if char.isdigit():
            if not first_number:
                first_number = char
                last_number = char
            else:
                last_number = char
    # Numbers generated by line
    nums.append(int(first_number+last_number))

# Results
print(sum(nums))
